# -*- coding: utf-8 -*-
"""concrete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KreCujbN9UjKzn0rXyl9rHY6YS6zXtM2
"""

# to delete folder
!rm -rf datasets

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

#%% import libraries

import os
import tensorflow as tf
import keras
import numpy as np
import matplotlib.pyplot as plt
import subprocess
import datetime
import tensorboard
from tensorflow.keras import layers, optimizers, initializers, regularizers, metrics, losses, activations, callbacks
from google.colab import files
from keras.models import load_model
from keras.utils import CustomObjectScope
from keras.utils import plot_model

!wget https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/5y9wdsg2zt-2.zip

# create a directory for the dataset
os.makedirs('dataset', exist_ok=True)
# List files in the current directory to verify the file name
!ls

!unzip "5y9wdsg2zt-2.zip"

!unrar x "Concrete Crack Images for Classification.rar" "/content/dataset"

# define constant
BATCH_SIZE = 32
IMG_SIZE = (256,256)
SEED = 42
INPUT_SHAPE = IMG_SIZE + (3,)
SAVE_MODEL_PATH = os.path.join("/content", "saved_models", "model.h5")

# Data Loading
EXTRACTED_DATASETS = "/content/dataset"
train = keras.utils.image_dataset_from_directory(EXTRACTED_DATASETS, validation_split=0.2, subset="training", batch_size=BATCH_SIZE, image_size=IMG_SIZE, seed=SEED, shuffle=True)
split = keras.utils.image_dataset_from_directory(EXTRACTED_DATASETS, validation_split=0.2, subset="validation", batch_size=BATCH_SIZE, image_size=IMG_SIZE, seed=SEED, shuffle=True)

# further split the 'split' into val and test

# investigate the batch size of 'split' first:
split_batches = tf.data.experimental.cardinality(split)
print(split_batches.numpy()) # found 250 batches

val = split.take((1*split_batches)//2)
test = split.skip((1*split_batches)//2)

# convert back to prefetchDataset
val = val.prefetch(buffer_size=tf.data.AUTOTUNE)
test = test.prefetch(buffer_size=tf.data.AUTOTUNE)

# Inspect datasets by plotting image
label_name = ["clean", "crack"]
for image_batch, label_batch in train.take(1):
    print(image_batch.shape)
    print(label_batch.shape)
    plt.figure(figsize=(10, 10))
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(image_batch[i].numpy().astype("uint8"))
        plt.title(label_name[label_batch[i]])
        plt.axis("off")

# Data Augmentation Function
def augment(image, label):
  image = tf.image.random_brightness(image, 0.4)
  image = tf.image.random_contrast(image, 0.1, 0.6)
  return image, label

# Apply data augmentation to the training dataset
train_dataset = train.map(augment, num_parallel_calls=tf.data.AUTOTUNE)
train_dataset = train_dataset.prefetch(buffer_size=tf.data.AUTOTUNE)

# Test the augmentation layers by visualizing the augmented images directly
plt.figure(figsize=(18, 10))
for images, label in train.take(1):
  first_image = images[0]
  plt.figure()
  for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    augmented_image, _ = augment(first_image, label[0])
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(augmented_image.numpy().astype("uint8")) # convert to uint8 for visualization
plt.show()

# Model Development

############## LIST OF MODELS FOR TRANSFER LEARNING ##################
# 1. MobileNetV2

################################################

# preprocessing layer
preprocessing_layer = keras.applications.mobilenet_v2.preprocess_input

# create the base model
base_model = keras.applications.MobileNetV2(weights="imagenet", include_top=False, input_shape=INPUT_SHAPE, pooling="avg")
base_model.trainable = False
base_model.summary()

# classification layer
output_layer = layers.Dense(2, activation='softmax')

# Arrange the entire model
# [A] - input layer
inputs = keras.Input(shape=INPUT_SHAPE)

# [B] - preprocessing layer
x = preprocessing_layer(inputs)

# [C] - pretrained layer for feature extractor
x = base_model(x)

# [D] - classification layer
outputs = output_layer(x)

# build the model
model = keras.Model(inputs=inputs, outputs=outputs)
model.summary()
#

# Compile the model
optimizer = optimizers.Adam(learning_rate=0.0001) #starts with small learning rate first
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# To investigate the effect of learning rate without training
print(model.evaluate(val))

# %% Model training
early_stopping = callbacks.EarlyStopping(monitor='val_loss', patience=2, verbose=1)
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

EPOCHS = 10
history_first = model.fit(train_dataset, validation_data=val, epochs=EPOCHS, callbacks=[early_stopping, tensorboard_callback]) # no need to supply batch size since its alr been done during data loading

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir logs

# check evaluation without further training
model.evaluate(val)

"""Already achieved high score without even further training the feature extractor.

## Further training the feature extractor layers
"""

base_model.trainable = True

# freeze earlier layers inside the base model, so that only the deeper level layers are trainable

print(len(base_model.layers)) # to see how many layers we have

fine_tune_at = ((9//10)*len(base_model.layers)) # out of 155 layers
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False # the first 75% layers will be untrainable

base_model.summary() # we can see the number of non trainable params have been reduced

model.summary()

print(len(history_first.epoch))
INITIAL_EPOCH = history_first.epoch[-1] # because we applied early_stopping
NEW_EPOCH = len(history_first.epoch) + 5 # total epochs altogether

# Continue the training
# we continue because we left at the history_first. and we pickup from where we left in training , after we have modify our base_mode

rmsprop = optimizers.RMSprop(learning_rate=0.00001) #even smaller learning rate
model.compile(optimizer=rmsprop, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# proceed with second stage training
history_fine_tune = model.fit(train, validation_data=test, epochs=NEW_EPOCH, initial_epoch=INITIAL_EPOCH, callbacks=[tensorboard_callback, early_stopping]) #notice that we dont start our epoch from 0.

"""We can see that with training few layers of the pretrained model, it does not even improve our accuracy score. however, our current model has already perform very well so we will stop here and evaluate our model before saving it."""

# Evaluate the model after training
print(model.evaluate(val))

# Use the model to make prediction, for simplicity we are going to predict only on the first batch
plt.figure(figsize=(10,10))
for image_batch, label_batch in val.take(1): # means take the first batch
    predictions = np.argmax(model.predict(image_batch), axis=1)
    print(predictions)
    predicted_class = [label_name[x] for x in predictions]
    print(predicted_class)
    for i in range(9):
        plt.subplot(3,3,i+1)
        plt.xticks([])
        plt.yticks([])
        plt.grid(False)
        plt.imshow(image_batch[i].numpy().astype('uint8'))
        plt.title(f"Actual: {label_name[label_batch[i]]}, Label: {predicted_class[i]}")
plt.show()

"""Every prediction is correct. Lets save our model"""

model.save(SAVE_MODEL_PATH)

# also save as keras because we have custom layer (keras preprocessing layer), so need to save in .keras otherwise will cause TrueDivide issue
model.save(os.path.join("/content", "saved_models", "model.keras"))

# Deployment
loaded_model = tf.keras.models.load_model('/content/saved_models/model.keras')
loaded_model.evaluate(test)

# plot the figure
plt.figure(figsize=(10,10))
for image_batch, label_batch in test.take(1): # means take the first batch
    predictions = np.argmax(model.predict(image_batch), axis=1)
    print(predictions)
    predicted_class = [label_name[x] for x in predictions]
    print(predicted_class)
    for i in range(9):
        plt.subplot(3,3,i+1)
        plt.xticks([])
        plt.yticks([])
        plt.grid(False)
        plt.imshow(image_batch[i].numpy().astype('uint8'))
        plt.title(f"Actual: {label_name[label_batch[i]]}, Label: {predicted_class[i]}")
plt.show()

# record classification report
from sklearn.metrics import classification_report
y_true = []
y_pred = []
for image_batch, label_batch in test:
    predictions = np.argmax(model.predict(image_batch), axis=1)
    y_true.extend(label_batch.numpy())
    y_pred.extend(predictions)
print(classification_report(y_true, y_pred, target_names=label_name))

# plot architecture of the model
plot_model(model, to_file='model_architecture.png', show_shapes=True, show_layer_names=True)